### ISSUE TITLE
Repo not populating on jellyfin

### ISSUE THREAD

**Issue by smurfhunter** [endrl/jellyfin-plugin-repo#1]
New to this so my troubleshooting capacity is limited. I combed my logs and could not find relevant lines or pieces to report. I will add a comment if that changes.

Multiple 3rd party repositories update fine and immediately upon being added to my Jellyfin, this one does not. Rebooted multiple times. 10.8.11 Jellyfin, installation is a stock Docker instance.

**Comment by vwillcox** [comment]
It because in the repo config and plugin config they are targeting Jellyfin 10.9 and the latest is 10.8.11

**Comment by endrl** [comment]
Currently you need a specific build of jellyfin-server to use it. I need to cleanup the api and push a proposal to the jellyfin-devs. I've read the meta discussion about the topic of merging it with chapters, which isn't done yet.

**Comment by DumberSoft** [comment]
> Currently you need a specific build of jellyfin-server to use it. I need to cleanup the api and push a proposal to the jellyfin-devs. I've read the meta discussion about the topic of merging it with chapters, which isn't done yet.

Now I understand, since at the moment of putting the repository nothing comes up to install.

**Comment by Dysta** [comment]
Hello, same issue here, any update about the situation ?

**Comment by endrl** [comment]
I added a docker compose file to spin up a test setup. It won't be compatible with your stable jellyfin setup. https://github.com/endrl/segment-editor#installation

**Comment by smurfhunter** [comment]
Works now
